name: permissions
version: '${project.version}'
main: me.kodysimpson.permissions.Permissions
api-version: '1.20'
commands:
  test:
    description: This is a test command
    permission: permissions.test
    permission-message: You do not have permission to run this command!
permissions:
  permissions.test:
    description: Allows someone to run the /test command
    default: op
    children:
      permissions.explode: true
      permissions.kill: true
  permissions.blockbreak:
    description: Allows someone to break a block